; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

# Environment for Tag
[env:uwb_tag]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
build_src_filter = +<setup_tag.cpp> -<NLOS_anchor.cpp>
upload_port = COM3
monitor_port = COM3

# Environment for Anchor
[env:uwb_anchor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
build_src_filter = +<NLOS_anchor.cpp> -<setup_tag.cpp>
upload_port = COM4
monitor_port = COM4
